import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
            crossorigin="anonymous"
          />
          <link href="/assets/styles.css" rel="stylesheet" />
      </Head>
        <body>
          <div class="d-flex justify-content-start mx-3 align-items-center mb-5">
            <img
              src="./assets/International_Pokémon_logo.svg.webp"
              alt="pokemon-logo"
              class="logo"
            />
            <div class="w-100">
              <h1 class="text-center">POKEDEX</h1>
            </div>
          </div>
          <div class="container mt-2">
            <div id="app" class="row"></div>
          </div>
          <script src="/prueba.js"></script>
          <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"
          ></script>
        </body>
    </div>
  )
}
